# Generated by Django 2.2.3 on 2019-07-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_of_anime', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cover', models.CharField(max_length=100)),
                ('self_description', models.TextField()),
                ('date_started', models.DateField()),
                ('date_finished', models.DateField()),
                ('op_rating', models.IntegerField()),
                ('ed_rating', models.IntegerField()),
                ('ost_rating', models.IntegerField()),
                ('overall_rating', models.IntegerField()),
                ('animeList', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animes.AnimeList')),
            ],
        ),
    ]
