# Generated by Django 2.2.3 on 2019-07-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0003_remove_animelist_amount_of_anime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='date_finished',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='date_started',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ed_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='op_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='ost_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='overall_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='self_description',
            field=models.TextField(null=True),
        ),
    ]
