# Generated by Django 2.2.3 on 2019-07-23 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0006_auto_20190722_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='date_finished',
            new_name='Date_Finished',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='date_started',
            new_name='Date_Started',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='ed_rating',
            new_name='ED_Rating',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='op_rating',
            new_name='OP_Rating',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='ost_rating',
            new_name='OST_Rating',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='overall_rating',
            new_name='Overall_Rating',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='self_description',
            new_name='Personal_Thoughts',
        ),
    ]
