# Generated by Django 2.2.1 on 2019-08-02 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0008_animelist_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelist',
            name='user_key',
        ),
    ]
