# Generated by Django 2.2.1 on 2019-08-03 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0009_remove_animelist_user_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='associated_token',
            field=models.TextField(blank=True),
        ),
    ]
