# Generated by Django 2.2.1 on 2019-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0011_remove_animelist_associated_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='animelist',
            name='associated_token',
            field=models.TextField(blank=True),
        ),
    ]
