# Generated by Django 2.2.1 on 2019-08-03 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0012_animelist_associated_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animelist',
            name='associated_token',
        ),
    ]
