# Generated by Django 2.2.1 on 2019-08-06 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0013_remove_animelist_associated_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='animeList',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnimeList',
        ),
    ]
