# Generated by Django 2.2.1 on 2019-08-06 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0014_auto_20190806_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='animeList',
            new_name='user',
        ),
    ]
