# Generated by Django 2.2.1 on 2019-08-06 17:25

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animes', '0015_auto_20190806_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='Date_Finished',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='Date_Started',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='ED_Rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='OP_Rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='OST_Rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='Overall_Rating',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='Personal_Thoughts',
        ),
        migrations.AddField(
            model_name='anime',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
