export const PREPARE_TO_DELETE = 'PREPARE_TO_DELETE'
export const STORE_TOKEN = 'STORE_TOKEN'
export const STORE_USERNAME = 'STORE_USERNAME'
export const STORE_ORDER_CHANGED_OR_REVERSED = 'STORE_ORDER_CHANGED_OR_REVERSED'