# Generated by Django 2.2.1 on 2019-08-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnimeList',
        ),
    ]
